version: '2'
services:
    stack-elasticsearch:
        image: elasticsearch:5.3.0
        ports:
            - "9300:9300"
            - "9200:9200"
        volumes:
            - ../elasticsearch/data:/usr/share/elasticsearch/data:rw
        environment:
            - ES_JAVA_OPTS=-Xmx1g -Xms1g
    stack-kibana:
        build: ../kibana/
        ports:
            - "5601:5601"
        depends_on:
            - stack-elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://stack-elasticsearch:9200
    stack-logstash:
        image: logstash:5.3.0
        depends_on:
            - stack-elasticsearch
        ports:
            - "5044:5044"
        command: logstash -f /var/lib/logstash/logstash.conf
        volumes:
            #- C:/inetpub/logs/LogFiles/:/accesslogs
            - ../logstash/:/var/lib/logstash