version: '2'
services:
    stack-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
        restart: always
    stack-kibana:
        build: kibana/
        depends_on:
            - stack-elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://stack-elasticsearch:9200
        volumes:
            - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml
        restart: always
    stack-nginx:
        image: nginx:1.11.8
        depends_on:
            - stack-elasticsearch
            - stack-kibana
        ports:
            - "80:80"
            - "9200:9200"
        volumes:
            - ./nginx/.htpasswd:/etc/nginx/.htpasswd
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
#    stack-logstash:
#        image: docker.elastic.co/logstash/logstash:5.2.1
#        depends_on:
#            - stack-elasticsearch
#        command: -f /opt/logstash/logstash.conf
#        volumes:
#            - ./logstash/:/opt/logstash
#        restart: always