version: '2'
services:
    stack-elasticsearch:
        image: elasticsearch:5.3.0
        ports:
            - "9300:9300"
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
        restart: always
    stack-kibana:
        build: kibana/
        depends_on:
            - stack-elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://stack-elasticsearch:9200
        restart: always
    stack-nginx:
        image: nginx:1.11.8
        depends_on:
            - stack-elasticsearch
            - stack-kibana
        ports:
            - "80:80"
            - "9200:9200"
        volumes:
            - ./nginx/.htpasswd:/etc/nginx/.htpasswd
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
    stack-logstash:
        image: logstash:5.3.0
        depends_on:
            - stack-elasticsearch
        ports:
            - "5044:5044"
        command: logstash -f /var/lib/logstash/logstash.conf
        volumes:
            - ./logstash/:/var/lib/logstash:rw
        restart: always